apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-efs-mariadb
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-efs-wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-wordpress
